### ISSUE TITLE
Version 2.1.11 does not work with patch 2.02

### ISSUE THREAD

**Issue by dieselvero** [DrJackieBright/CP77-External-Radio-red4ext#9]
Version 2.1.11 says that it should work for patch 2.02, but it does not.  It throws the following error:

_"Cyberpunk 2077 encountered an error caused by a corrupted or missing scripts file and will now be forced to close.

Outdated mods or traces of old mods are possible causes..... "_

**Comment by DrJackieBright** [comment]
didn't see this here, 2.1.11 was broken, version 2.1.12 is now the correct version for 2.02
